// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPshCh5b45hN2zAVytByC22W_NFdvCmZg',
    appId: '1:279365912827:web:783552d1d4a431b75c885e',
    messagingSenderId: '279365912827',
    projectId: 'fluttertask-ad3db',
    authDomain: 'fluttertask-ad3db.firebaseapp.com',
    storageBucket: 'fluttertask-ad3db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA8DAlnclpD36bvJXh4pXv96dsQmI5Wh8',
    appId: '1:279365912827:android:9e61849cc6a10c9f5c885e',
    messagingSenderId: '279365912827',
    projectId: 'fluttertask-ad3db',
    storageBucket: 'fluttertask-ad3db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCt5e2PchEichlUMhQ3uSpRbA_iPu4bVs',
    appId: '1:279365912827:ios:c3da256e37bd15f25c885e',
    messagingSenderId: '279365912827',
    projectId: 'fluttertask-ad3db',
    storageBucket: 'fluttertask-ad3db.appspot.com',
    iosBundleId: 'com.example.fltask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCt5e2PchEichlUMhQ3uSpRbA_iPu4bVs',
    appId: '1:279365912827:ios:c3da256e37bd15f25c885e',
    messagingSenderId: '279365912827',
    projectId: 'fluttertask-ad3db',
    storageBucket: 'fluttertask-ad3db.appspot.com',
    iosBundleId: 'com.example.fltask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPshCh5b45hN2zAVytByC22W_NFdvCmZg',
    appId: '1:279365912827:web:f5f74a8012deaa375c885e',
    messagingSenderId: '279365912827',
    projectId: 'fluttertask-ad3db',
    authDomain: 'fluttertask-ad3db.firebaseapp.com',
    storageBucket: 'fluttertask-ad3db.appspot.com',
  );
}
